// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: todo.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos(account_id, title, content, priority)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateTodoParams struct {
	AccountID pgtype.UUID
	Title     string
	Content   string
	Priority  Priority
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.AccountID,
		arg.Title,
		arg.Content,
		arg.Priority,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
