basePath: /
info:
  contact: {}
  title: Todo API
  version: "1.0"
paths:
  /:
    get:
      description: check if server is running
      produces:
      - application/json
      responses: {}
swagger: "2.0"
