basePath: /
info:
  contact: {}
  title: Todo API
  version: "1.0"
paths:
  /:
    get:
      description: test if server is ok
      produces:
      - application/json
      responses: {}
swagger: "2.0"
