basePath: /
definitions:
  database.CreateAccountParams:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  server.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  title: Todo API
  version: "1.0"
paths:
  /:
    get:
      description: Check if server is running
      produces:
      - application/json
      responses: {}
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login with email and password
      parameters:
      - description: Registration payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/server.LoginRequest'
      responses:
        "200":
          description: Created account ID
          schema:
            type: string
      summary: Login
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Creates a new user account with email and password
      parameters:
      - description: Registration payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/database.CreateAccountParams'
      responses:
        "200":
          description: Created account ID
          schema:
            type: string
      summary: Create a new account
      tags:
      - auth
swagger: "2.0"
